### ISSUE TITLE
[BUG][Registration] Error when registering new account, username doesn't meet length requirements.

### ISSUE THREAD

**Issue by CapnFlint** [uee-life/uee.life.next#281]
```[Fri, 25 Oct 2024 19:35:18 GMT]-[API-CALL]-[Anonymous] http://127.0.0.1/api/user/create [POST]
{
  code: 'CF54-5C74',
  email: 'clonetrooper619@gmail.com',
  handle: 'Azula_Blackthorne'
}
[Fri, 25 Oct 2024 19:35:18 GMT]-[NEO4J-Write]-[Anonymous] MATCH (c:InviteCode)        WHERE c.code = $code ...
[Fri, 25 Oct 2024 19:35:18 GMT]-[NEO4J-Write]-[Anonymous] MATCH (c:InviteCode)                WHERE c.code ...
creating account
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5UY3hRemM1TWtWR09URkZSalkzTVRJek1FUTRNemRGTkRVNFFqY3lORGswT0RVNU5VSkZNZyJ9.eyJpc3MiOiJodHRwczovL3VlZWxpZmUuYXV0aDAuY29tLyIsInN1YiI6IjZMUDM4RUpuc0VoZVdBNGdNOVI5YnZWOWZ2aUlUdWNIQGNsaWVudHMiLCJhdWQiOiJodHRwczovL3VlZWxpZmUuYXV0aDAuY29tL2FwaS92Mi8iLCJpYXQiOjE3Mjk4MTk1NTcsImV4cCI6MTcyOTkwNTk1Nywic2NvcGUiOiJyZWFkOnVzZXJzIHVwZGF0ZTp1c2VycyBkZWxldGU6dXNlcnMgY3JlYXRlOnVzZXJzIHJlYWQ6dXNlcnNfYXBwX21ldGFkYXRhIHVwZGF0ZTp1c2Vyc19hcHBfbWV0YWRhdGEgZGVsZXRlOnVzZXJzX2FwcF9tZXRhZGF0YSBjcmVhdGU6dXNlcnNfYXBwX21ldGFkYXRhIGNyZWF0ZTp1c2VyX3RpY2tldHMgcmVhZDpjb25uZWN0aW9ucyByZWFkOnJ1bGVzIHJlYWQ6cnVsZXNfY29uZmlncyByZWFkOnN0YXRzIHJlYWQ6bG9ncyByZWFkOmxvZ3NfdXNlcnMgcmVhZDpncmFudHMgcmVhZDplbWFpbF90ZW1wbGF0ZXMgcmVhZDptZmFfcG9saWNpZXMgcmVhZDpyb2xlcyByZWFkOmxvZ19zdHJlYW1zIHJlYWQ6c2lnbmluZ19rZXlzIHJlYWQ6cm9sZV9tZW1iZXJzIHJlYWQ6ZW50aXRsZW1lbnRzIHJlYWQ6YXR0YWNrX3Byb3RlY3Rpb24gcmVhZDphdXRoZW50aWNhdGlvbl9tZXRob2RzIHJlYWQ6cmVmcmVzaF90b2tlbnMiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiI2TFAzOEVKbnNFaGVXQTRnTTlSOWJ2VjlmdmlJVHVjSCJ9.ttsNh7ie3VgeJei09dnoGgD_LzD4E-u5hUJfUsRVTfwhmBDcoWT2Z0qi9-jpw4__oguWvvo_qAq2VQ8y1U--9GoWgZuJk16RPEjNq-1f4rKjogyBJb4KabTodv79728gXb6126IZygKtDm3xrlZtq01uQ-dqTK7lRDlQjIonefgihssS7hm3GvA1SpSl62unf26CDon-Alh64HfSghD1J5mUMeGy9knNWiUv_vUyIeClpmQPG0js6YKaHJXR7o-eJES3i7p6m1uV7qft_OEMFxwtTS48Y4Q9S5m57mZCGvPuzQ2W6yzRdI0CzlMEnFOZoCcpYuicUVeymI3eCcejuA
creating account
{
  statusCode: 400,
  error: 'Bad Request',
  message: `Payload validation error: '"username" does not meet length criteria.'.`,
  errorCode: 'invalid_body'
}
getting reset token
FetchError: [POST] "https://ueelife.auth0.com/api/v2/users": 400 Bad Request
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetch2 (file:///src/.output/server/chunks/runtime.mjs:3722:15)
    at async createAccount (file:///src/.output/server/chunks/_/auth0.mjs:198:19)
    at async checkAndCreateUser (file:///src/.output/server/chunks/routes/api/user/create.post.mjs:51:9)
    at async Object.handler (file:///src/.output/server/chunks/routes/api/user/create.post.mjs:42:7)
    at async Object.handler (file:///src/.output/server/chunks/runtime.mjs:3158:19)
    at async Server.toNodeHandle (file:///src/.output/server/chunks/runtime.mjs:3428:7)
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'user_id')
  at createAccount (./server/chunks/_/auth0.mjs:222:24)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async checkAndCreateUser (./server/chunks/routes/api/user/create.post.mjs:51:9)
  at async Object.handler (./server/chunks/routes/api/user/create.post.mjs:42:7)
  at async Object.handler (./server/chunks/runtime.mjs:3158:19)
  at async Server.toNodeHandle (./server/chunks/runtime.mjs:3428:7)
```

**Comment by CapnFlint** [comment]
I found the issue. The default configuration for username length is 1-15 characters. As we are using their email as their username, anyone with an email longer than 15 characters got bounced. I have updated this to 50 characters (overkill, but to be safe), which should resolve this issue!
