### ISSUE TITLE
[Bug] RSI Fetch Failed

### ISSUE THREAD

**Issue by CaptNemoUK** [uee-life/uee.life.next#74]
ERROR  [POST] "https://robertsspaceindustries.com/api/hub/getCommlinkItems": <no response> fetch failed

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (/C:/Users/Nemo/Documents/GitHub/uee.life.next/app/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)
  at fetchNews (server\api\news\index.get.js:36:1)
  at Object.handler (server\api\news\index.get.js:13:1)
  at async /C:/Users/Nemo/Documents/GitHub/uee.life.next/app/node_modules/h3/dist/index.mjs:1962:19
  at async Object.callAsync (/C:/Users/Nemo/Documents/GitHub/uee.life.next/app/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (/C:/Users/Nemo/Documents/GitHub/uee.life.next/app/node_modules/h3/dist/index.mjs:2249:7)

**Comment by CapnFlint** [comment]
RSI issue
