### ISSUE TITLE
[Bug] Create Citizen Error

### ISSUE THREAD

**Issue by CaptNemoUK** [uee-life/uee.life.next#75]
ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'find')
  at createCitizen (C:\Users\Nemo\Documents\GitHub\uee.life.next\app\server\utils\citizen.js:77:26)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at getCitizen (C:\Users\Nemo\Documents\GitHub\uee.life.next\app\server\utils\citizen.js:19:17)
  at Object.handler (C:\Users\Nemo\Documents\GitHub\uee.life.next\app\server\api\user\index.get.js:13:1)
  at async /C:/Users/Nemo/Documents/GitHub/uee.life.next/app/node_modules/h3/dist/index.mjs:1962:19
  at async Object.callAsync (/C:/Users/Nemo/Documents/GitHub/uee.life.next/app/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (/C:/Users/Nemo/Documents/GitHub/uee.life.next/app/node_modules/h3/dist/index.mjs:2249:7)

**Comment by CapnFlint** [comment]
RSI issue
